### ISSUE TITLE
Term & conditions missing when registering

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-catencomu#35]
After the oauth registering, terms and conditions are empty!

**Comment by verarojman** [comment]
https://github.com/decidim/decidim/pull/6716

**Comment by verarojman** [comment]
Closed by [30c9bfd](https://github.com/Platoniq/decidim-catencomu/commit/30c9bfdd6dc288c7aa67be3d969a2def14b6e6ea)
