### ISSUE TITLE
Allow admins to restrict comments to verfied users

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-catencomu#37]
This is accepted for core:
https://meta.decidim.org/processes/roadmap/f/122/proposals/15785

Inspiration:
https://github.com/decidim/decidim/pull/5274/files

Tasks:
- [x] PR to `decidim/decidim/develop` https://github.com/decidim/decidim/pull/6916
- [x] Backported to `platoniq/temp/0.22-surveys` through https://github.com/Platoniq/decidim/pull/38 (deployed)
- [x] Backport to `platoniq/temp/0.23` @microstudi 
- [x] use branch  `platoniq/temp/0.23` in catcomu repo

dependent on #36  for deploying

**Comment by verarojman** [comment]
Closed by #47
