### ISSUE TITLE
Actualització versió 0.24

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-catencomu#59]
Actualitzar a la versió 0.24 (https://github.com/decidim/decidim/blob/release/0.24-stable/CHANGELOG.md)

- [x] Staging: testparticipa.catalunyaencomu.cat/
- [x] Producció: comunitat.catalunyaencomu.cat/
- [x] Video explicatiu: https://www.loom.com

**Comment by verarojman** [comment]
Closed by #61
