### ISSUE TITLE
Processes index view is broken without processes to be shown

### ISSUE THREAD

**Issue by aitorlb** [Platoniq/decidim-catencomu#81]
Processes path should display empty index view instead of 404 when no processes are visible for the current user.

-  Path:`/`

![Screenshot from 2021-08-04 10-15-20](https://user-images.githubusercontent.com/40306853/128146679-3234e169-fcd1-4c9c-a03c-6fae180f6fa5.png)

- Path: `/processes`

![Screenshot from 2021-08-04 10-14-34](https://user-images.githubusercontent.com/40306853/128146570-874d8c65-9d1e-4a41-a975-1e9187481725.png)

**Comment by marta-platoniq** [comment]
Fixed via issue #99
