### ISSUE TITLE
Fix grups d'administració acotats

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-catencomu#82]
He fet una mica de tasteig a https://testparticipa.catalunyaencomu.cat/processes_groups/1. 

Problemes que he detectat:

- [ ] Si sóc un administrador de grup de processos, no hauria de poder veure tot el menú del tauler de configuració
- [x] Si sóc un administrador de grup de processos **Alt Pirineu i Aran**, no hauria de poder gestionar processos participatius que no estan relacionats (ex: programa electoral)
- [x] Si sóc un administrador de grup de processos, haig de poder editar la Pàgina d'Inici del grup de processos
- [x] Si sóc un administrador de grup de processos, haig de poder crear nous processos participatius que només es poden vincular al grup de processos que adminstro

Dentro video

https://user-images.githubusercontent.com/40388743/128155514-e6429325-b858-41e7-9202-f5dff3c48132.mp4

**Comment by microstudi** [comment]
Way to fix this:

- allow awesome to access admin processes list when admin scoped admin only to processes groups
- create a custom admin menu that allows any scoped admin to a process group to:
   - create a new process in that group and be admin in it
   - create a new consultation

**Comment by microstudi** [comment]
ok, aixo hauria d'estar solucionat via #83

**Comment by marta-platoniq** [comment]
Si la última versió és la que hi ha a testparticipa.catalunyaencomu.cat , l'item "Si sóc un administrador de grup de processos, no hauria de poder veure tot el menú del tauler de configuració" en general funciona, menys en els següents casos, el els quals veig totes les opcions del tauler de configuració:

- Quan accedeixo al tauler de control mitjançant la opció "Tauler d'administració" del menú d'usuari
- Quan des de l'admin clico "Tauler de control" o "Processos"

Si clico Managers, Moderacions globals o Butlletins, el menú sí que està correctament restringit. També està restringit quan edito un procés en particular.

https://user-images.githubusercontent.com/72607737/142670035-fc02a915-30e8-48a4-9cae-fbf91d316b24.mov

**Comment by microstudi** [comment]
La veritat es que aixo no té una resolució fàcil per un tema tècnic. Ho investigarem a veure si trobem alguna truc

**Comment by microstudi** [comment]
L'ultima versió hauria d'homogeneitzar el menu per als admins acotats @marta-platoniq ! penjat a staging

**Comment by marta-platoniq** [comment]
Síiii! I ho fa molt bé :) He vist q també has tret moderacions globals i butlletins de la vista acotada, super i moltes gràcies!

Tanquem, doncs?

**Comment by microstudi** [comment]
@marta-platoniq si tota la resta esta be, podem fer el merge, publiquem i tanquem
