### ISSUE TITLE
Blog s'ha d'acotar per processos del seu grup de processos

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-catencomu#87]
Amb el bloc [Ultimes entrades al blog] es mostren les publicacions del blog que hi ha (les més recents).
El problema, és que encara que faci una entrada en el grup de processos Alt Pirineu i Aran, també es mostra als altres grups de processos. 
Per tant, el bloc només hauria d'agafar de font els processos que tenen blogs del seu grup de processos. 
M'he explicat bé?
https://user-images.githubusercontent.com/40388743/135866684-411a4c36-85af-4c5a-8026-10e3062e93c9.mp4

**Comment by marta-platoniq** [comment]
Hola! A mi amb la correcta configuració del camp "component" dins de l'edició del bloc "Últimes entrades del blog" de la pàgina d'inici, em funciona correctament:

![Screenshot 2021-11-10 at 19 15 52](https://user-images.githubusercontent.com/72607737/141170563-cdaa89cb-749a-4073-a0ba-0ebf4950d56d.png)

He entès bé el teu problema? Pots comprovar si el segueixes tenint?

**Comment by marta-platoniq** [comment]
Resolt
