### ISSUE TITLE
Server error en reportar com inapropiada una proposta que prové d'una trobada

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-catencomu#96]
Crec que pot ser un bug del propi Decidim, però no ho he pogut comprovar, així que de moment ho deixo aquí:

https://user-images.githubusercontent.com/72607737/143498007-a9e1b735-a82f-4f14-a7ab-6f0ab43498d6.mov

**Comment by marta-platoniq** [comment]
Comprovat, és un bug de Decidim. També passa a la última versió (v0.25).

Reportat aquí : https://github.com/decidim/decidim/issues/8568.

**Comment by microstudi** [comment]
@marta-platoniq gracies!
