### ISSUE TITLE
Si no estic logejada, no veig la pàgina principal d'àmbits territorials

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-catencomu#99]
Si no estic logejada, en clicar "Àmbits territorials" al menú, o provar d'entrar a : [https://testparticipa.catalunyaencomu.cat/processes](https://testparticipa.catalunyaencomu.cat/processes)

em mostra un error:

![image](https://user-images.githubusercontent.com/72607737/146966995-e4943ecc-d2b5-4b42-a7dd-271a9f574701.png)

Què hauria de passar?
M'hauria de mostrar el mapa dels àmbits territorials, per poder accedir a la pàgina d'inici dels diferents àmbits, als quals sí hi puc accedir.

**Comment by marta-platoniq** [comment]
@marta-platoniq @ivanverges aq error crec q s'hauria d'arreglar per catencomu (per quan t'hi fiquis)

**Comment by marta-platoniq** [comment]
Ja sé com ho podem arreglar, i matem dos pájarus d'un tir.

Si creem un procés public on allotjar el blog d'actualitat, en seleccionar àmbits territorials ja es veu el mapa i es pot seleccionar el grup de processos i, a més a més, les entrades al blog Actualitat són públiques.

**Comment by paarals** [comment]
> pájarus
com a concepte, m'encanta

**Comment by marta-platoniq** [comment]
Resolt amb la creació del procés públic Blog 🎉
